### PR TITLE
minimal changes to work with current symfony/process

### PR DESCRIPTION
**Pull request by darkalchemy**

### CODE REVIEW

**Comment by darkalchemy** [comment]
I have test this in my current project darkalchemy/slim-auth and I didn't see any errors or issues.

Thanks for this, it makes folder permissions easy and constant.

**Comment by umpirsky** [comment]
Thanks!

**Comment by darkalchemy** [comment]
Thanks @umpirsky 
One more request, could you bump the version so composer will grab the changes?

**Comment by umpirsky** [comment]
Done https://github.com/umpirsky/PermissionsHandler/releases/tag/v1.6.

**Comment by darkalchemy** [comment]
Thanks a bunch!

**Comment by darkalchemy** [comment]
I'm sorry to keep bothering you, but could update [packagist,](https://packagist.org/packages/umpirsky/composer-permissions-handler) its not auto updating.

Thanks again

**Comment by umpirsky** [comment]
Done!

**Comment by darkalchemy** [comment]
Thanks!!

**Pull request merged**
